version: '4'
services:
  myslq:
    image: mysql:8.3.0
    container_name: inventory-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql